# Sesi 4

In [2]:
import numpy as np

In [3]:
print(np.array.__doc__)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memo

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
print(np.zeros.__doc__)

zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
print(np.ones.__doc__)


    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of ones with the given sha

In [9]:
dim = (3,3)
np.ones(dim)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
print(np.empty.__doc__)

empty(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    --

In [11]:
np.empty(dim)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
print(np.arange.__doc__)

arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections below for more information.

    Parameters
    ----------
    star

In [15]:
print(np.arange(4))

[0 1 2 3]


In [16]:
np.arange(3)
print(np.arange(0,5)) #(start,end, step)

[0 1 2 3 4]


In [17]:
np.arange(0,5.5)

array([0., 1., 2., 3., 4., 5.])

In [18]:
np.array([1,2])
np.zeros(3)
np.empty(4)
np.arange(4)
np.ones(3)

array([1., 1., 1.])

## add remove and sort

In [19]:
#append
arr =np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.append(arr, [1,2])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
#delete
arr = np.delete(arr, 1)
arr

array([1, 4, 5, 6, 7, 8])

In [27]:
#sort
arr2 = np.array([2,5,6,3,8])
arr2

array([2, 5, 6, 3, 8])

In [28]:
np.sort(arr2)

array([2, 3, 5, 6, 8])

## shape and size

In [29]:
array_example = np.array([
    np.arange(3),
    np.arange(3,6),
    np.arange(6,9)
])
array_example

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
print(array_example.ndim)

2


In [33]:
print(array_example.size)

9


In [34]:
print(array_example.shape)

(3, 3)


In [35]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [36]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [37]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [38]:
#you can use np.newaxis to add new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [39]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [40]:
#you can convert a 1D array to row vector by inserting an axis along the firts dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [41]:
#for a colummn vector, you can insert axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Creating Array from Exiting Data

In [42]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

## VSTACK

In [44]:
a_1 = np.array([
    [1,1],
    [2,2]
])

In [45]:
a_2 = np.array([
    [3,3],
    [4,4]
])

In [46]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# Or stack them horizontally with stack

np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## HSPLIT

In [48]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], 
       [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [49]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [50]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
# you can create a new array object that looks at the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a = np.array([1,2,3,4])

# Add all of the elements in the array
a.sum()

10

In [54]:
# untuk menambhakan baris/kolom dalam array 2D

b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [55]:
b.sum(axis=0)

array([3, 3])

In [56]:
b.sum(axis=1)

array([2, 4])

In [57]:
data = np.array([1,2])
data

array([1, 2])

In [58]:
ones = np.ones(2)
ones

array([1., 1.])

In [59]:
data + ones

array([2., 3.])

In [60]:
data * data

array([1, 4])

In [61]:
data / data

array([1., 1.])

In [62]:
data * 2

array([2, 4])

## More Array Operations
data.max() data.min() data.sum()

In [63]:
A = np.array([
                [0.786836, 0.837644, 0.5263652, 0.635424],
                [0.12, 0.343, 0.6377, 0.6352443],
                [0.6367736, 0.98765, 0.1323, 0.8763]
            ])
print(A)

[[0.786836  0.837644  0.5263652 0.635424 ]
 [0.12      0.343     0.6377    0.6352443]
 [0.6367736 0.98765   0.1323    0.8763   ]]


In [64]:
A.sum()

7.1552371

In [65]:
A.min()

0.12

In [66]:
A.min(axis=0)

array([0.12     , 0.343    , 0.1323   , 0.6352443])

In [67]:
A.max()

0.98765

In [68]:
A.max(axis=1)

array([0.837644, 0.6377  , 0.98765 ])

In [69]:
A.std()

0.2651594771050982

## Matrix Arithmetic

In [70]:
#Kita dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika
# jika kedua matriks tersebut sama. NumPy menanganinya sebagai position-wise operations.

data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [71]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [72]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [73]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [74]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product
NumPy memberi setiap matriks metode dot() yang dapat kita gunakan untuk menjalankan operasi dot product dengan matriks lain.

In [75]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [76]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

In [77]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Transposing and Reshaping

Kebutuhan umum saat menangani matriks adalah kebutuhan untuk rotate. Hal ini sering terjadi ketika kita perlu melakukan dot product dari 2 matriks dan perlu menyelaraskan dimensi mereka. Array NumPy memiliki properti yang disebut T untuk mendapatkan traspos dari sebuah matriks.

In [79]:
print(data)

[[1 2]
 [3 4]
 [5 6]]
